spring:
  application:
    name: CloudDisk

  datasource:
    url: jdbc:mysql://localhost:3306/cloud?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: gtly30jcio!
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.clouddisk.model

logging:
  level:
    com.example.clouddisk: DEBUG
    com.zaxxer.hikari: DEBUG